# Funding platforms for Cellular Threshold
# These are displayed in the "Sponsor" button on GitHub

# github:
#   - smith6jt-cop

# patreon: cellular-threshold

# ko_fi: cellularthreshold

# custom:
#   - https://www.buymeacoffee.com/cellularthreshold
